spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lushan?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lushan
    password: jA72YaANS6WHJRts
  aop:
    auto: true
    proxy-target-class: true
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
server:
  port: 8849
  servlet:
    context-path: /lushan
lushan:
  history-data-root: /www/wwwroot/lushan_data/lushan_datasets/historyDatasets
  history-dataset-picture: /www/wwwroot/lushan_data/lushan_datasets/historyDatasetsPicture
  current-data-root: /www/wwwroot/lushan_data/lushan_datasets/currentDatasets
  proof-root: /www/wwwroot/lushan_data/upload/user_proof
  buffer-data-root: /www/wwwroot/lushan_data/download
  comment-root: /www/wwwroot/lushan_data/upload/comment
  link-root: http://106.13.10.209:8851
  secret: "dfc1b985bc618ebbff54d08f3e067bc4" # jwt秘钥


