spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lushan?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Gh19990624!
  aop:
    auto: true
    proxy-target-class: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
server:
  port: 8081
  servlet:
    context-path: /lushan

lushan:
  history-data-root: E:/lushan_server/datasets/historyDatasets
  history-dataset-picture: E:/lushan_server/datasets/historyDatasetsPicture
  current-data-root: E:/lushan_server/datasets/currentDatasets
  proof-root: E:/lushan_server/upload/user_proof
  buffer-root: http://10.23.107.96:8848/lushan_front/data/
  buffer-data-root: E:/lushan_server/download
  secret: "dfc1b985bc618ebbff54d08f3e067bc4" # jwt秘钥
  comment-root: E:/lushan_server/upload/comment


