spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lushan?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Gh19990624!
  aop:
    auto: true
    proxy-target-class: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
server:
  port: 8080
  servlet:
    context-path: /lushan
fastdep:
  shiro-jwt:
    secret: "6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52" # jwt秘钥
#    expireTime: 7200000 # token有效期
#    prefix: "Bearer "  # token校验时的前缀
#    signPrefix: "Bearer " # token生成签名的前缀
#    header: "Authorization" # token校验时的header头
#    以下对应为shiro配置参数，无特殊需求无需配置
#    loginUrl:
#    successUrl:
#    unauthorizedUrl:
#    filterChainDefinitions:
lushan:
  data-root: D:/lushan_server/upload/data
  proof-root: D:/lushan_server/upload/user_proof